version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
